export const REGISTER_USER = "REGISTER_USER"
export const SIGN_USER = "SIGN_USER"
export const AUTO_SIGN_IN = 'AUTO_SIGN_IN'
export const GET_ARTICLES = 'GET_ARTICLES'
export const ADD_ARTICLES = 'ADD_ARTICLES'
export const RESET_ARTICLE = "RESET_ARTICLE"
export const GET_USER_POST = "GET_USER_POST"
export const DELETE_USER_POST = "DELETE_USER_POST"